events {}
http {
    include /etc/nginx/mime.types; # DIT PROBLEEM LOSKOPPELEN: laadt JS/CSS goed in!
    
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html;
            auth_basic "Beveiligde pagina";
            auth_basic_user_file /etc/nginx/.htpasswd;
        }
    }
}
